# Generated by Django 6.0.4 on 2026-06-04 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Enquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=254)),
                ("project_type", models.CharField(max_length=100)),
                ("budget", models.CharField(max_length=100)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Enquiry",
                "verbose_name_plural": "Enquiries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Kitchen", "Kitchen"),
                            ("Bedroom", "Bedroom"),
                            ("Furniture", "Furniture"),
                            ("Office Interior", "Office Interior"),
                            ("Walls & Ceiling", "Walls & Ceiling"),
                            ("Lighting", "Lighting"),
                        ],
                        max_length=50,
                    ),
                ),
                ("image", models.ImageField(upload_to="products/")),
                ("description", models.TextField()),
                ("price", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "Pro",
            },
        ),
    ]
