# Generated by Django 6.0.4 on 2026-06-04 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interior", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="enquiry",
            name="location",
            field=models.CharField(default="Tezpur", max_length=100),
        ),
        migrations.AddField(
            model_name="enquiry",
            name="status",
            field=models.CharField(
                choices=[("pending", "⏳ Pending"), ("done", "✅ Completed")],
                default="pending",
                max_length=20,
            ),
        ),
    ]
