# Generated by Django 6.0.4 on 2026-06-04 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interior", "0002_enquiry_location_enquiry_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="GalleryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="e.g., Grand Living Room", max_length=100
                    ),
                ),
                ("image", models.ImageField(upload_to="gallery/")),
                (
                    "grid_class",
                    models.CharField(
                        choices=[
                            ("g1", "Large Highlight (g1)"),
                            ("g2", "Medium Vertical (g2)"),
                            ("g3", "Small Square Top (g3)"),
                            ("g4", "Medium Horizontal (g4)"),
                            ("g5", "Small Square Bottom (g5)"),
                            ("g6", "Wide Base Row (g6)"),
                        ],
                        default="g1",
                        help_text="Controls the layout structure in the grid mosaic",
                        max_length=2,
                    ),
                ),
                (
                    "order",
                    models.IntegerField(default=0, help_text="Ascending sort order"),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
    ]
